### ISSUE TITLE
Error when exporting papers with Em-Dash?

### ISSUE THREAD

**Issue by moffat** [jdidion/papers2#4]
When exporting to zotero using papers2zotero, I see many errors like:

```
ERROR:root:Error converting publication 4157 to Zotero
Traceback (most recent call last):
  File "/Users/cmoffat/anaconda3/envs/python2/bin/papers2zotero.py", line 105, in main
    if z.add_pub(pub):
  File "/Users/cmoffat/anaconda3/envs/python2/lib/python2.7/site-packages/papers2/zotero.py", line 308, in add_pub
    value = EXTRACTORS[key].extract(pub, self, value)
  File "/Users/cmoffat/anaconda3/envs/python2/lib/python2.7/site-packages/papers2/zotero.py", line 62, in extract
    value = self.format_tuple(value, nvals)
  File "/Users/cmoffat/anaconda3/envs/python2/lib/python2.7/site-packages/papers2/zotero.py", line 90, in format_tuple
    return ("{0}-{1}".format(*values),)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 3: ordinal not in range(128)
```

There's a reference and solution to this [here](https://stackoverflow.com/questions/40039212/ascii-codec-cant-encode-character-u-u2013). 

Thanks.

**Comment by jdidion** [comment]
Closing — this repo is being archived.
