### ISSUE TITLE
No module named 'ConfigParser'

### ISSUE THREAD

**Issue by andhou** [jdidion/papers2#5]
I get the following error in MacOS terminal with Python 3.9.5
>> python3 papers2zotero.py --config config.txt

Traceback (most recent call last):
  File "/Users/andershougaard/Downloads/papers2-main/bin/papers2zotero.py", line 8, in <module>
    from papers2.schema import Papers2, Label
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/papers2/schema.py", line 15, in <module>
    from .util import enum
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/papers2/util.py", line 8, in <module>
    from ConfigParser import SafeConfigParser as ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'

**Comment by jdidion** [comment]
Closing — this repo is being archived.
